create table if not exists public.respostas_multi_controle (
  id bigint generated by default as identity primary key,
  codigo_loja text not null,
  codigo_vendedor text not null,
  nome_gn text not null,
  produto_ofertado text not null,
  sondagem_residencial text not null,
  elegibilidade_multi text not null,
  motivo_nao_venda text not null,
  apoio_conversao text not null,
  explicacao text not null,
  enviado_em timestamptz not null default now()
);
alter table public.respostas_multi_controle enable row level security;
create policy "Permitir somente novos envios" on public.respostas_multi_controle for insert to anon with check (true);
